### ISSUE TITLE
Divida sobre a Ficha de Tormenta 20

### ISSUE THREAD

**Issue by Painisio** [rrpgfirecast/firecast#110]
A ficha de Tormenta 20 é compatível com a versão anterior do jogo? Digo anteriormente existia uma ficha em .dll, contudo acredito que ela não mais funcione no Firecast! Inclusive tentei upar aqui a bendita, acredite ainda tenho essa reliquia, mas o formato não é suportado pelo github!

**Comment by VinnyAmbesek** [comment]
Fichas de dll não são mais suportadas pelo Firecast.
Qual ficha de tormenta 20 se refere? Talvez seja melhor falar diretamente com quem a fez.
