### ISSUE TITLE
Instalação de fontes

### ISSUE THREAD

**Issue by astroty** [rrpgfirecast/firecast#15]
O script de instalação do RRPG para Ubuntu/Debian (e derivados) se utiliza das seguintes linhas para a instalação de fontes:

```
silent_eval "sudo mkdir -p /usr/local/share/fonts/ms_fonts"
silent_eval "sudo cp $RRPG_INSTALL_DIRECTORY/wine/fonts/*.ttf /usr/local/share/fonts/ms_fonts/"
silent_eval "sudo chmod 644 /usr/local/share/fonts/ms_fonts/* -R"
silent_eval "sudo chmod 755 /usr/local/share/fonts/ms_fonts"
silent_eval "sudo fc-cache -fv"
```
O RRPG não necessita instalar fontes a nível de sistema, bastando que elas sejam instaladas dentro da pasta pessoal do usuário. 
Se não me engano, o local padrão para fontes pessoais é em ~/.fonts/

```
silent_eval "mkdir -p ~/.fonts/ms_fonts"
silent_eval "cp $RRPG_INSTALL_DIRECTORY/wine/fonts/*.ttf ~/.fonts/ms_fonts"
(Preciso de confirmação de root necessário) silent_eval "fc-cache -fv"
```

**Comment by TyrasNistru** [comment]
Me lembro de ter lido que algumas distros (e algumas versões do ubuntu/debian) tem problemas com o wine caso as fontes não estejam instaladas a nível de sistema. Além disso, o local de instalação de fontes a nível de usuário varia de distro para distro, e alguns DEs também usam diretórios diferentes, causando ainda mais dor de cabeça.

Preferi não arriscar, visto que não é um problema tão grande assim. Afinal, o maior "problema" é a necessidade de acesso root, o que já é necessário de qualquer forma.

**Comment by astroty** [comment]
O instalador não foi feito para ser utilizado em distros que não foram baseadas em Debian pelo fato de ele utilizar apt-get, por isso a sugestão

Mas acho que o comun comun mesmo para fontes de usuário é o caminho  ~/.local/share/fonts

**Comment by TyrasNistru** [comment]
Sim, mas mesmo entre distros baseadas no debian isso pode mudar. E o que não faltam são distros baseadas nele, direta ou indiretamente, e entre os usuários menos "profissionais", elas imperam. Daí a escolha.

De qualquer forma, é um problema instalar a nível de sistema? Como elas são instaladas numa subpasta, facilmente removível, não vejo realmente necessidade de arriscar um mal-funcionamento do RR num ambiente já difícil de adaptar para o RR. Mas se há um problema, ou uma complicação real para o sistema ou para o usuário, podemos repensar no caso.

**Comment by astroty** [comment]
Bem, nesse caso, acho que tudo bem mesmo!
Não teria a opção das fontes serem instaladas pelo pacote ttf-mscorefonts-installer?

**Comment by TyrasNistru** [comment]
De início, o script usava o winetricks para instalar as fontes só no wine, através dos pacotes do próprio winetricks, mas essas fontes são bugadas em tamanhos menores que 13pt, daí essas fontes instaladas manualmente. 

De início pensei no ttf-mscorefonts-installer, mas se não me engano, o winetricks usa o mesmo pacote, daí cairia no mesmo problema. Não cheguei a testar, preferi pegar as fontes nativas e instalar diretamente.
