### ISSUE TITLE
Problema instalando a ficha.

### ISSUE THREAD

**Issue by CaioFSoares** [rrpgfirecast/firecast#16]
Boa noite. 

Primeiramente, desculpe se falhei em instalar algo. Tentei instalar da mesma forma que instalei a ficha de CoC e 5E mas por algum motivo não funciona. 

`
[Cyberpunk2020/01.General.lfm] Assertion failure (D:\sd\rrpg\Bibliotecas\CL.FMX\RRPG.TypeWriter.Win32DirectWrite.pas, line 577)

CallStack:
  /sdk/rrpgLFM.lua [linha 18]
`

Esse é o erro que aparece quando tento instalar a ficha direto pro .bat quando transformo o rpk em uma pasta.

**Comment by CaioFSoares** [comment]
Postei no local errado.

**Comment by alyssonrpg** [comment]
Esse ocorre durante a execução do comando "rdk i" ?

**Comment by CaioFSoares** [comment]
Sim, tb acontece caso tente executar o arquivo "compilar e instalar.bat".

Testei hoje em outro computador após uma instalação limpa do RRPG Firecast e funcionou quando baixei pelo link no [README.md](https://github.com/rrpgfirecast/firecast/blob/master/Plugins/Sheets/README.md)

**Comment by CaioFSoares** [comment]
"Resolvi".
Abri a ficha na versão 7.3b e ela abriu normalmente no computador original.
Obrigado!
