### ISSUE TITLE
Ataques Avançados

### ISSUE THREAD

**Issue by oouo-diogo-perdigao** [rrpgfirecast/firecast#25]
A seleção de armas dos ataques avançados não esta funcionando.
![REF1](https://user-images.githubusercontent.com/16609076/99899920-7a5e2a80-2c8b-11eb-861a-db1a7eb617ff.png)
![ref2](https://user-images.githubusercontent.com/16609076/99899921-7af6c100-2c8b-11eb-8cc3-d0e0e801d61a.png)

**Comment by VinnyAmbesek** [comment]
As armas dos ataques avançados são as listadas no inventario. Não existe comunicação entre ataques avançados e simples.

**Comment by oouo-diogo-perdigao** [comment]
Desculpe, na documentação dava a entender outra coisa. Erro meu =D
Pode fechar o topico
