### ISSUE TITLE
Ficha D&D 4e

### ISSUE THREAD

**Issue by gladuriel** [rrpgfirecast/firecast#42]
Olá senhores, notei que nos plugins não temos a ficha de D&D 4e (se tem, não achei). Eu sei que não é uma edição muito popular, mas ainda temos alguns grupos que jogam... Terá a ficha? No Firecast 8, no caso.

**Comment by VinnyAmbesek** [comment]
Se alguém fizer vai ter. 
Observe que a maioria dos plugins aqui não são nativos do Firecast, mas feito pelos usuários.
